### Recuperar todas las peliculas 

GET http://localhost:1234/movies 



### Recuperar una pelicula por su id

GET http://localhost:1234/movies/1º



### Recuperar una pelicula por género

GET http://localhost:1234/movies?genre=terror 

// ? es un cor parametro



